// SPDX-License-Identifier: GPL-3.0-or-later
import QtQuick
import QtQuick.Controls
import QtQuick.Layouts
AppDialog {
    id: guide; objectName: "tutorialDialog"; title: "Tutorial & workflow guide"; preferredWidth: 640
    property int topic: 0
    readonly property var lessons: [
        { title: "Start here", body: "NandStudio edits and runs projects locally. Files manages your workspace, Build processes the active source, Machine displays simulation state, and Console shows results. On a phone, use the four pane tabs.\n\nChoose Files > Create course workspace for an editable copy of the original projects and four independent examples. Original course files remain intact. This preview does not yet provide complete Java or web IDE parity." },
        { title: "Open, edit and save", body: "Choose Files > Open workspace, then select a document in Files. Edit in the Editor pane. Save writes the active document; Files > Save all writes open documents. An unsaved indicator marks changed buffers.\n\nMore > Find and replace opens search. Settings offers a font picker, size, indentation, wrapping, theme and autosave. Recovery stays enabled. If another application changes a file, resolve the conflict before saving." },
        { title: "Android workspaces", body: "Choose Files > Open workspace and grant access in Android's folder chooser. Confirm Import copy. Editing and Save update NandStudio's local copy, not the provider's original folder.\n\nUse Files > Export workspace copy to export saved results to a new folder. Export important work before uninstalling or clearing app data. Providers and physical devices are not all qualified. Files and More must appear below the system status bar." },
        { title: "Projects 1–2: gates and arithmetic", body: "Open examples/EntryAlarm.hdl in a course workspace and press Build. In Machine, set enabled=1 and door=1, then press Eval. The expected alarm is 1. Set door=0 and window=0, then Eval; alarm becomes 0.\n\nFor Xor, inputs 0/1 or 1/0 produce 1. Equal inputs produce 0. Local Not, And and Or files override built-ins, including empty starter implementations. Follow dependency warnings and complete those chips; the simulator does not silently replace student work.\n\nOpen a chip's .tst and run its HDL test action to compare against .cmp. Console reports errors and generated output." },
        { title: "Project 3: sequential circuits", body: "Use examples/RememberBit for an independent sequential example. Edit input pins, then use Tick and Tock to advance the two clock phases. Eval alone does not replace a full clock cycle. Inspect pins and internal state after each phase.\n\nComplete the supplied sequential coursework in its ordinary folders. Reload explicitly after changing HDL; this can reset sequential state. Complete inspector and script-debugging parity is still pending." },
        { title: "Projects 4–6: assembly and CPU", body: "Open .asm and press Build to create .hack from the visible buffer. Open the generated program and choose Load CPU in Machine. Step one instruction, inspect registers and memory, or run a batch. Stop interrupts execution.\n\nUse CPU test actions for supplied .tst programs. Keep expected .cmp files unchanged. Machine includes screen, keyboard and breakpoint controls; keyboard input must be directed to the simulated screen. Project 5 also uses HDL composition, ROM loading and clock operations. Incremental assembler and full component visualization parity remain open." },
        { title: "Projects 7–8: VM execution", body: "Open a .vm file and choose Load VM. The containing directory supplies related VM files. Step and inspect the current instruction, stack, frame pointers and call stack. Use VM test actions for VM .tst scripts.\n\nBuild on a VM source generates assembly using the added native translator. This convenience is separate from the original desktop VM Emulator and does not complete the translator assignment. Calls, statics and project-local dependencies must retain their ordinary file layout." },
        { title: "Projects 9–11: Jack programs", body: "Open a .jack file. Build compiles the visible source to .vm. For a multi-file program, choose More > Converters & diagnostics > Compile Jack folder. This includes unsaved open sibling Jack buffers without saving their source. All sources compile before outputs are committed; dirty VM buffers and external output changes block replacement.\n\nInspect diagnostics, then explicitly Load VM to run the generated program. Building does not reset an already running simulation. Project 10 syntax analysis and full compiler diagnostic parity remain incomplete; the original Jack compiler does not make every coursework utility a legacy feature." },
        { title: "Project 12: operating system", body: "Keep your OS implementations beside the application VM files. More > Add supplied Jack OS can explicitly copy the eight bundled OS VM files and notice into the active folder. Existing files, including empty student versions, are preserved. Load VM afterward.\n\nThe supplied VM files are a runnable reference, not native built-in service fallback. Full built-in selection, confirmation and service parity remain unfinished. This action does not complete the OS assignment." },
        { title: "Converters, bitmap and diagnostics", body: "More > Converters & diagnostics provides numeric conversion, source previews and optional live diagnostics. Preview does not replace the running machine. Click a diagnostic to navigate to its source.\n\nMore > Bitmap editor lets you draw, resize, shift, flip, invert and undo/redo. Choose Jack or ASM and copy generated code into an ordinary source file. Save that source before closing; drawings are not yet restored after restart. Image import and animation export remain open." },
        { title: "Troubleshooting and next steps", body: "Eval still shows zero: check the displayed inputs, press Eval, inspect dependency warnings, and verify local starter chips contain implementations. A parser error must be resolved before replacing the last valid machine.\n\nBuild fails: use the first diagnostic and check relative files, local implementations and writable output folders. Android changes are missing elsewhere: Save, then Export the local workspace copy.\n\nThe repository's docs/TODO.md and parity-manifest.json track remaining work. All 12 course workflows and full web IDE parity are not yet certified. The guides and demonstrations describe tested behavior, not a promise that every feature is complete." }
    ]
    contentItem: ColumnLayout {
        ComboBox { objectName: "tutorialTopicPicker"; Layout.fillWidth: true; model: guide.lessons.map(item => item.title); currentIndex: guide.topic; onActivated: guide.topic=currentIndex; Accessible.name: "Tutorial topic" }
        ScrollView {
            id: page; Layout.fillWidth: true; Layout.fillHeight: true; implicitHeight: 330; clip: true; contentWidth: availableWidth
            Label { objectName: "tutorialBody"; width: page.availableWidth; text: guide.lessons[guide.topic].body; color: Theme.text; wrapMode: Text.WordWrap; padding: Theme.sm }
        }
        Label { text: (guide.topic+1)+" / "+guide.lessons.length; color: Theme.muted }
    }
    footer: RowLayout {
        ActionButton { objectName: "tutorialPrevious"; text: "Previous"; enabled: guide.topic>0; onClicked: {guide.topic--;page.contentItem.contentY=0} }
        ActionButton { objectName: "tutorialNext"; text: "Next"; enabled: guide.topic<guide.lessons.length-1; onClicked: {guide.topic++;page.contentItem.contentY=0} }
        ActionButton { text: "Done"; onClicked: guide.accept() }
    }
}
